blank_issues_enabled: true
contact_links:
  - name: Webb Telegram
    url: https://t.me/tanglenet
    about: Please ask questions here.
  - name: Webb Discord Server
    url: https://discord.com/invite/cv8EfJu3Tn
    about: Please ask and answer questions here.
